# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: VEM AI !!
description: ""
index_title: "E QUEM VEM AI ?"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# modals itens to use o _includes/menu.html and _includes/modal.html
modal_title: "Qual nome você acha que é ?"
modals:
  - link: "claudiel"
    label: "Claudiel"
    img: "/assets/images/claudiel.webp"
    text: "Não inventa moda !!"
    home: "true"
  - link: "musk" 
    label: "X$ Alter"
    img: "/assets/images/musk.jpg"
    text: "Sério ?"
    home: "true"
  - link: "cecilia"
    label: "Cecilia"
    img: "/assets/images/ammy.gif"
    text: "Será ?"
    home: "true"
    target:
      link: "#bolo"
      label: Tem certeza ?
  - link: "neiael" 
    label: "Neia-El"
    img: "/assets/images/neiael.jpg"
    text: "Os advogados da DC não liberaram"
    home: "true"
  - link: "otto"
    label: "Otto"
    img: "/assets/images/peralta.gif"
    text: "Será ?"
    home: "true"
    target:
      link: "#no"
      label: Tem certeza ?
  - link: "gabrineia"
    label: "Gabrineia" 
    home: "true"
    img: "/assets/images/gabrineia.webp"
    text: "Melhor não né..."
  - link: "#bolo"
    img: "/assets/images/green.webp"
    text: "HEYYYY CECI VEM AI !!!!!"
  - link: "#no"
    img: "/assets/images/no.gif"
    text: "NÃO É ESSE, TENTA DE NOVO !!"

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - CNAME
