theme: jekyll-bootstrap-theme
title: Vem ai
description: Vem ai
#### LAYOUT OPTIONS #####

# Half layout
half_side: center



# Full layout
full_text_position: center # left, right or center
markdown: kramdown

plugin:
  - jekyll-responsive-image
  - jekyll-remote-theme

remote_theme: jonaharagon/jekyll-bootstrap-theme@v1.1.0

responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html #THIS ONE

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
